apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- rollout.yaml
- service.yaml
- canary-service.yaml
images:
- name: ghcr.io/atidyshirt/golfapp-dotgolf-service
  newName: ghcr.io/atidyshirt/golfapp-dotgolf-service
  newTag: 14a12e0a4a9f87c2e5d85d9f68f32b5e760ad1bb
