apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- rollout.yaml
- service.yaml
- canary-service.yaml
- httproute.yaml
- canary-httproute.yaml

images:
- name: ghcr.io/atidyshirt/golfapp-web
  newName: ghcr.io/atidyshirt/golfapp-web
  newTag: 386ec821a31ab27c08221af4fa7359c0baee7b40
