apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- rollout.yaml
- service.yaml
- canary-service.yaml
- httproute.yaml
- canary-httproute.yaml

images:
- name: ghcr.io/atidyshirt/golfapp-web
  newName: ghcr.io/atidyshirt/golfapp-web
  newTag: b6d101609df8c3d04d9791cfe39069dfcf0f6431
