apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- rollout.yaml
- service.yaml
- canary-service.yaml
images:
- name: ghcr.io/atidyshirt/golfapp-dotgolf-service
  newName: ghcr.io/atidyshirt/golfapp-dotgolf-service
  newTag: 0399fd6f0a5036a777cf2696529951f3af5f4759
