apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - api
  - web
  - dotgolf-service
  - postgres

components:
  - api/components/replacements
  - web/components/replacements
