apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- rollout.yaml
- service.yaml
- canary-service.yaml
- httproute.yaml
- canary-httproute.yaml
- onepassword-item.yaml

images:
- name: ghcr.io/atidyshirt/golfapp-api
  newName: ghcr.io/atidyshirt/golfapp-api
  newTag: 8620c5d3661164324ddd5403b33a334816d19a0e
