apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- rollout.yaml
- service.yaml
- canary-service.yaml
images:
- name: ghcr.io/atidyshirt/golfapp-coursepack-service
  newName: ghcr.io/atidyshirt/golfapp-coursepack-service
  newTag: unreleased
