apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../api
  - ../web
  - ../postgres-preview
  - onepassword-item.yaml

patches:
  - target:
      kind: Service
      name: golfapp-api-preview
    patch: |-
      $patch: delete
      apiVersion: v1
      kind: Service
      metadata:
        name: golfapp-api-preview
  - target:
      kind: HTTPRoute
      name: golfapp-api-preview
    patch: |-
      $patch: delete
      apiVersion: gateway.networking.k8s.io/v1
      kind: HTTPRoute
      metadata:
        name: golfapp-api-preview
  - target:
      kind: HTTPRoute
      name: golfapp-api
    patch: |-
      $patch: delete
      apiVersion: gateway.networking.k8s.io/v1
      kind: HTTPRoute
      metadata:
        name: golfapp-api
  - target:
      kind: AnalysisTemplate
      name: golfapp-api-health-check
    patch: |-
      $patch: delete
      apiVersion: argoproj.io/v1alpha1
      kind: AnalysisTemplate
      metadata:
        name: golfapp-api-health-check
  - target:
      kind: OnePasswordItem
      name: oidc-dex
      namespace: golf
    patch: |-
      $patch: delete
      apiVersion: onepassword.com/v1
      kind: OnePasswordItem
      metadata:
        name: oidc-dex
        namespace: golf
  - target:
      kind: Service
      name: golfapp-web-preview
    patch: |-
      $patch: delete
      apiVersion: v1
      kind: Service
      metadata:
        name: golfapp-web-preview
  - target:
      kind: HTTPRoute
      name: golfapp-web-preview
    patch: |-
      $patch: delete
      apiVersion: gateway.networking.k8s.io/v1
      kind: HTTPRoute
      metadata:
        name: golfapp-web-preview
  - target:
      kind: AnalysisTemplate
      name: golfapp-web-health-check
    patch: |-
      $patch: delete
      apiVersion: argoproj.io/v1alpha1
      kind: AnalysisTemplate
      metadata:
        name: golfapp-web-health-check
  - target:
      kind: Rollout
      name: golfapp-api
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/strategy
        value:
          canary: {}
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
  - target:
      kind: Rollout
      name: golfapp-web
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/strategy
        value:
          canary: {}
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: 25m
            memory: 32Mi
          limits:
            cpu: 100m
            memory: 128Mi
